---
- name: Converge
  hosts: all
  tasks:
    - name: Include hydrusnetwork
      ansible.builtin.import_role:
        name: hyuugi.ushizaki.hydrusnetwork

    - name: Include poetry
      ansible.builtin.import_role:
        name: hyuugi.ushizaki.poetry
