---
- name: Install required packages
  ansible.builtin.dnf:
    name: git
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install required packages
  ansible.builtin.apt:
    name: git
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Acquire Hydrus Network source code
  ansible.builtin.git:
    repo: https://github.com/hydrusnetwork/hydrus.git
    dest: "{{ git_repository_directory }}"
    version: "{{ git_repository_version }}"
