---
- name: Install required packages (RedHat)
  become: true
  ansible.builtin.dnf:
    name:
      - ffmpeg-free
      - git
      - python3.9
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Install required packages (Debian)
  become: true
  ansible.builtin.apt:
    name:
      - ffmpeg
      - git
      - python3-venv
    state: present
    update_cache: true
  when: ansible_facts["os_family"] == "Debian"

- name: Acquire Hydrus Network source code
  ansible.builtin.git:
    repo: https://github.com/hydrusnetwork/hydrus.git
    dest: "{{ git_repository_directory }}"
    version: "{{ git_repository_version }}"

- name: Update pip within Hydrus Network venv
  ansible.builtin.pip:
    name:
      - pip
    virtualenv: "{{ virtual_environment_directory }}"
    virtualenv_command: "{{ virtual_environment_command }}"
    extra_args: --upgrade

- name: Update wheel within Hydrus Network venv
  ansible.builtin.pip:
    name:
      - wheel
    virtualenv: "{{ virtual_environment_directory }}"
    virtualenv_command: "{{ virtual_environment_command }}"
    extra_args: --upgrade
