---
- name: Ushizaki - Deploy the Hydrus Network
  hosts: localhost
  tasks:
    - name: Import hydrusnetwork role
      ansible.builtin.import_role:
        name: hyuugi.ushizaki.hydrusnetwork

    - name: Import hydownloader role
      ansible.builtin.import_role:
        name: hyuugi.ushizaki.hydownloader
